const anime = ["2.5 Dimensional Seduction ", "3D Kanojo: Real Girl ", "86 (Eighty-Six)", "A Couple of Cuckoos", "A Sign of Affection", "A Silent Voice", "Aharen Is Indecipherable", "Akame ga Kill", "Aho Girl", "Angel Beats", "Another", "Another Layer", "Ao no Hako", "Apotheker's Diary", "Arifureta: From Commonplace to World's Strongest", "Boku no Kokoro no Yabai Yatsu", "Black Clover", "Blue Box", "Blue Spring Ride", "Call of the Night", "Cautious Hero: The Hero is Overpowered but Overly Cautious", "Charlotte", "Chained Soldier", "Chivalry Of A Failed Knight", "Clannad: After Story", "Danmachi", "Death Parade", "Dororo", "Fate", "Fire Force", "Food Wars", "Fruits Basket", "Full Metal Panic", "Gushing Over Magical Girls", "Grand Blue", "Hellsing", "Hellsing Ultimate", "Hibike! Euphonium", "High School DxD", "High School of the Dead", "Hige wo Soru", "Hotarubi no Mori e", "Hyakkano", "I Killed Slimes for 300 Years and Maxed Out My Level", "I Want to Eat Your Pancreas", "Juliet of Boarding School", "Kaguya-sama: Love Is War", "Killing Bites", "Kimi ni Todoke", "KonoSuba: God's Blessing on This Wonderful World!", "Kurakon", "Lazarus", "Link Click", "Make Heroine", "Maid Sama", "Masamune-kun's Revenge", "Medakawa", "Mob Psycho 100", "More Than a Married Couple", "But Not Lovers", "My Happy Marriage", "My Little Monster", "Mystery Disappearances", "Nisekoi", "No Game No Life", "Oregairu", "Oshi no Ko", "Our Dating Story", "Overlord", "Perfect Blue", "Plastic Memories", "Pop Team Epic", "Pseudo Harem", "Re:Zero", "ReLIFE", "Renai Flops", "Rent-a-Girlfriend", "Ride Your Wave", "Sakurasou no Pet na Kanojo ", "Sakamoto Desu ga?", "Say I Love You", "Shangri-La Frontier", "Shikimori: Not Just a Cutie", "Shimoneta", "Sounds of Life", "Spice and Wolf", "Steins;Gate", "Summer Ghost", "Suzume", "Tasogare Otome x Amnesia", "Takt op.Destiny", "The 100 Girlfriends Who Really, Really, Really, Really, Really Love You", "The Angel Next Door", "The Beginning After the End", "The Café Terrace and Its Goddesses", "The Dangers in My Heart", "The Future Diary", "The Most Notorious Evil Runs the World's Greatest Clan", "The Rising of the Shield Hero", "The Tunnel to Summer", "To Love Ru", "Tomodachi ame", "Tonikaku Kawaii", "Tying the Knot With an Amagami Sister", "Violet Evergarden", "Weathering With You", "We never Learn", "Welcome to the NHK", "Why the Hell Are You Here, Teacher!?", "Wind Breaker", "Wotakoi", "Yona Of The Dawn", "Your Lie in April", "Your Name"];
const serie = ["1899", "A Killer Paradox", "Alice in Borderland", "All Of Us Are Dead", "Arrow", "Band Of Brothers", "Behind Her Eyes", "Breaking Bad", "Buffy The Vampire Slayer", "Chernobyl", "Clickbait", "Cobra Kai", "Dept.Q", "Dexter", "Deli Boys", "Daredevil", "Echoes", "Empire", "From", "Fubar", "Game Of Thrones", "Ginny and Georgia", "Godless", "Goodfellas", "H/Jack", "How To Sell Drugs Online", "Lupin", "Mad Men", "Manifest", "Midnight Mass", "Mindhunter", "Money Heist", "Never Have I Ever", "Night Has Come", "Outer Banks", "Ozark", "Peaky Blinders", "Person of Interest", "Prison Break", "Pyramid Game", "Shameless", "Snowfall", "Stranger From Hell", "Stranger Things", "Succession", "Supacell", "Swagger", "The 100", "The Boys", "The Cage", "The Gentlemen", "The Godfather", "The Leftovers", "The Office", "The Sinner", "The Sopranos", "The Walking Dead", "The Witcher", "Twin Peaks", "Umbrella Academy", "Vigilante", "Vikings", "Warrior", "Weak Hero", "S.W.A.T."];
const filme = [ "Inception", "The Dark Knight", "Avengers: Endgame", "Pulp Fiction", "Forrest Gump", "The Matrix", "Gladiator", "Interstellar", "The Lord of the Rings: The Fellowship of the Ring", "The Shawshank Redemption", "Fight Club", "The Godfather", "The Silence of the Lambs", "Jurassic Park", "Titanic", "Saving Private Ryan", "Schindler's List", "The Prestige","The Lion King", "Back to the Future", "Star Wars: Episode IV - A New Hope", "The Avengers","Iron Man", "Black Panther", "Doctor Strange", "Guardians of the Galaxy", "The Hunger Games","Twilight", "Avatar", "Mad Max: Fury Road", "The Revenant", "Django Unchained", "Whiplash", "La La Land", "Parasite", "Joker", "The Departed", "Shutter Island", "Oldboy", "The Grand Budapest Hotel", "Moonlight", "Her", "Eternal Sunshine of the Spotless Mind", "The Social Network", "Catch Me If You Can", "Knives Out", "The Imitation Game", "Logan", "Deadpool", "Guardians of the Galaxy Vol. 2", "Thor: Ragnarok", "Spider-Man: No Way Home", "Black Swan", "Requiem for a Dream", "A Quiet Place", "It", "Get Out", "Us", "The Conjuring", "Saw", "Insidious", "Midsommar", "Doctor Zhivago", "Gone with the Wind",  "Casablanca", "La Dolce Vita", "12 Years a Slave", "Dune", "The Shining", "The Thing", "Hereditary"];
function randomize(list) {
    return list[Math.floor(Math.random() * list.length)];
}
document.querySelector(".rot").addEventListener("click", () => {
    document.querySelector(".rot").style.backgroundImage = `url('https://dummyimage.com/1000x500/000/fff&text=${randomize(anime)}')`;
});
document.querySelector(".blau").addEventListener("click", () => {
    document.querySelector(".blau").style.backgroundImage = `url('https://dummyimage.com/1000x500/000/fff&text=${randomize(filme)}')`;
});
document.querySelector(".grün").addEventListener("click", () => {
    document.querySelector(".grün").style.backgroundImage = `url('https://dummyimage.com/1000x500/000/fff&text=${randomize(serie)}')`;
});